// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: 2026 Samuel

#include "sysctlkcm.h"

#include <KAuth/Action>
#include <KAuth/ExecuteJob>
#include <KPluginFactory>

SysctlKcm::SysctlKcm(QObject *parent, const KPluginMetaData &metaData)
    : KQuickConfigModule(parent, metaData)
    , m_model(new SysctlModel(this))
{
    setButtons(Apply | Default);
    setAuthActionName(QStringLiteral("org.kde.fcse.write"));
}

void SysctlKcm::save()
{
    const QVariantList entries = m_model->modifiedEntries();

    // Build the content string in sysctl key = value format
    QString content = QStringLiteral("# Generated by Fedora Core Setting Extension\n");
    for (const auto &entry : entries) {
        const QVariantMap map = entry.toMap();
        content += map[QStringLiteral("key")].toString()
                + QStringLiteral(" = ")
                + map[QStringLiteral("value")].toString()
                + QLatin1Char('\n');
    }

    QVariantMap args;
    args[QStringLiteral("filePath")] = QStringLiteral("/etc/sysctl.d/99-fcse.conf");
    args[QStringLiteral("content")] = content.toUtf8();
    args[QStringLiteral("postCommand")] = QStringLiteral("/usr/sbin/sysctl");
    args[QStringLiteral("postArgs")] = QStringList{QStringLiteral("--system")};

    KAuth::Action action(QStringLiteral("org.kde.fcse.write"));
    action.setHelperId(QStringLiteral("org.kde.fcse"));
    action.setArguments(args);

    KAuth::ExecuteJob *job = action.execute();
    connect(job, &KJob::result, this, [this, job] {
        if (job->error()) {
            qWarning() << "KAuth write failed:" << job->errorString();
        } else {
            // Reload to reflect the applied changes
            m_model->reload();
        }
        setNeedsSave(false);
    });
    job->start();
}

void SysctlKcm::load()
{
    m_model->reload();
    setNeedsSave(false);
}

K_PLUGIN_CLASS_WITH_JSON(SysctlKcm, "kcm_fcse_sysctl.json")

#include "sysctlkcm.moc"
