#include "configparser.h"

#include <QFile>
#include <QRegularExpression>
#include <QTextStream>

namespace NsaFsm {

// --- sysctl: key = value ---

QList<SysctlEntry> ConfigParser::parseSysctl(const QString &filePath)
{
    QList<SysctlEntry> entries;
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return entries;
    }

    QTextStream in(&file);
    while (!in.atEnd()) {
        QString line = in.readLine().trimmed();
        if (line.isEmpty() || line.startsWith(QLatin1Char('#'))) {
            continue;
        }
        const int eq = line.indexOf(QLatin1Char('='));
        if (eq < 0) {
            continue;
        }
        SysctlEntry entry;
        entry.key = line.left(eq).trimmed();
        entry.value = line.mid(eq + 1).trimmed();
        entries.append(entry);
    }
    return entries;
}

bool ConfigParser::writeSysctl(const QString &filePath, const QList<SysctlEntry> &entries)
{
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        return false;
    }

    QTextStream out(&file);
    out << QStringLiteral("# Generated by NSA Fedora System Manager\n");
    for (const auto &entry : entries) {
        out << entry.key << QStringLiteral(" = ") << entry.value << QLatin1Char('\n');
    }
    return true;
}

// --- /etc/hosts ---

QList<HostsEntry> ConfigParser::parseHosts(const QString &filePath)
{
    QList<HostsEntry> entries;
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return entries;
    }

    QTextStream in(&file);
    while (!in.atEnd()) {
        QString line = in.readLine();
        QString trimmed = line.trimmed();

        if (trimmed.isEmpty()) {
            continue;
        }

        // Comment-only line: preserve as entry with empty ip
        if (trimmed.startsWith(QLatin1Char('#'))) {
            HostsEntry entry;
            entry.comment = trimmed;
            entries.append(entry);
            continue;
        }

        // Split off inline comment
        QString comment;
        QString data = trimmed;
        const int hashPos = data.indexOf(QLatin1Char('#'));
        if (hashPos >= 0) {
            comment = data.mid(hashPos).trimmed();
            data = data.left(hashPos).trimmed();
        }

        const QStringList parts = data.split(QRegularExpression(QStringLiteral("\\s+")), Qt::SkipEmptyParts);
        if (parts.size() < 2) {
            continue;
        }

        HostsEntry entry;
        entry.ip = parts.at(0);
        entry.hostnames = parts.mid(1);
        entry.comment = comment;
        entries.append(entry);
    }
    return entries;
}

bool ConfigParser::writeHosts(const QString &filePath, const QList<HostsEntry> &entries)
{
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        return false;
    }

    QTextStream out(&file);
    for (const auto &entry : entries) {
        // Comment-only line
        if (entry.ip.isEmpty() && entry.hostnames.isEmpty()) {
            out << entry.comment << QLatin1Char('\n');
            continue;
        }

        out << entry.ip << QLatin1Char('\t') << entry.hostnames.join(QLatin1Char(' '));
        if (!entry.comment.isEmpty()) {
            out << QLatin1Char('\t') << entry.comment;
        }
        out << QLatin1Char('\n');
    }
    return true;
}

// --- /etc/fstab ---

QList<FstabEntry> ConfigParser::parseFstab(const QString &filePath)
{
    QList<FstabEntry> entries;
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return entries;
    }

    QTextStream in(&file);
    while (!in.atEnd()) {
        QString line = in.readLine();
        QString trimmed = line.trimmed();

        if (trimmed.isEmpty()) {
            continue;
        }

        // Comment-only line
        if (trimmed.startsWith(QLatin1Char('#'))) {
            FstabEntry entry;
            entry.comment = trimmed;
            entries.append(entry);
            continue;
        }

        const QStringList parts = trimmed.split(QRegularExpression(QStringLiteral("\\s+")), Qt::SkipEmptyParts);
        if (parts.size() < 6) {
            continue;
        }

        FstabEntry entry;
        entry.device = parts.at(0);
        entry.mountpoint = parts.at(1);
        entry.fstype = parts.at(2);
        entry.options = parts.at(3);
        entry.dump = parts.at(4).toInt();
        entry.pass = parts.at(5).toInt();
        entries.append(entry);
    }
    return entries;
}

bool ConfigParser::writeFstab(const QString &filePath, const QList<FstabEntry> &entries)
{
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        return false;
    }

    QTextStream out(&file);
    for (const auto &entry : entries) {
        // Comment-only line
        if (!entry.comment.isEmpty() && entry.device.isEmpty()) {
            out << entry.comment << QLatin1Char('\n');
            continue;
        }

        out << entry.device << QLatin1Char('\t')
            << entry.mountpoint << QLatin1Char('\t')
            << entry.fstype << QLatin1Char('\t')
            << entry.options << QLatin1Char('\t')
            << entry.dump << QLatin1Char('\t')
            << entry.pass << QLatin1Char('\n');
    }
    return true;
}

// --- KEY=VALUE (GRUB, /etc/environment) ---

QMap<QString, QString> ConfigParser::parseKeyValue(const QString &filePath)
{
    QMap<QString, QString> values;
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return values;
    }

    QTextStream in(&file);
    while (!in.atEnd()) {
        QString line = in.readLine().trimmed();
        if (line.isEmpty() || line.startsWith(QLatin1Char('#'))) {
            continue;
        }
        const int eq = line.indexOf(QLatin1Char('='));
        if (eq < 0) {
            continue;
        }
        const QString key = line.left(eq).trimmed();
        QString value = line.mid(eq + 1).trimmed();

        // Strip surrounding quotes
        if (value.length() >= 2) {
            if ((value.startsWith(QLatin1Char('"')) && value.endsWith(QLatin1Char('"')))
                || (value.startsWith(QLatin1Char('\'')) && value.endsWith(QLatin1Char('\'')))) {
                value = value.mid(1, value.length() - 2);
            }
        }

        values.insert(key, value);
    }
    return values;
}

bool ConfigParser::writeKeyValue(const QString &filePath, const QMap<QString, QString> &values)
{
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        return false;
    }

    QTextStream out(&file);
    out << QStringLiteral("# Generated by NSA Fedora System Manager\n");
    for (auto it = values.constBegin(); it != values.constEnd(); ++it) {
        const QString &val = it.value();
        if (val.contains(QLatin1Char(' ')) || val.contains(QLatin1Char('\t'))) {
            out << it.key() << QStringLiteral("=\"") << val << QStringLiteral("\"\n");
        } else {
            out << it.key() << QLatin1Char('=') << val << QLatin1Char('\n');
        }
    }
    return true;
}

// --- INI format ([section] + key=value) ---

QMap<QString, QMap<QString, QString>> ConfigParser::parseIni(const QString &filePath)
{
    QMap<QString, QMap<QString, QString>> sections;
    QFile file(filePath);
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return sections;
    }

    QString currentSection;
    QTextStream in(&file);
    while (!in.atEnd()) {
        QString line = in.readLine().trimmed();
        if (line.isEmpty() || line.startsWith(QLatin1Char('#')) || line.startsWith(QLatin1Char(';'))) {
            continue;
        }

        // Section header
        if (line.startsWith(QLatin1Char('[')) && line.endsWith(QLatin1Char(']'))) {
            currentSection = line.mid(1, line.length() - 2).trimmed();
            if (!sections.contains(currentSection)) {
                sections.insert(currentSection, {});
            }
            continue;
        }

        // key=value within a section
        const int eq = line.indexOf(QLatin1Char('='));
        if (eq < 0) {
            continue;
        }
        const QString key = line.left(eq).trimmed();
        const QString value = line.mid(eq + 1).trimmed();
        sections[currentSection].insert(key, value);
    }
    return sections;
}

bool ConfigParser::writeIni(const QString &filePath, const QMap<QString, QMap<QString, QString>> &sections)
{
    QFile file(filePath);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text | QIODevice::Truncate)) {
        return false;
    }

    QTextStream out(&file);
    bool first = true;
    for (auto secIt = sections.constBegin(); secIt != sections.constEnd(); ++secIt) {
        if (!first) {
            out << QLatin1Char('\n');
        }
        first = false;

        out << QLatin1Char('[') << secIt.key() << QStringLiteral("]\n");
        const auto &kvMap = secIt.value();
        for (auto kvIt = kvMap.constBegin(); kvIt != kvMap.constEnd(); ++kvIt) {
            out << kvIt.key() << QStringLiteral(" = ") << kvIt.value() << QLatin1Char('\n');
        }
    }
    return true;
}

} // namespace NsaFsm
