// SPDX-License-Identifier: GPL-2.0-or-later
// SPDX-FileCopyrightText: 2026 Samuel

#include "environmentkcm.h"
#include "configparser.h"

#include <KAuth/Action>
#include <KAuth/ExecuteJob>
#include <KPluginFactory>

#include <QDir>
#include <QFile>
#include <QStandardPaths>

EnvironmentKcm::EnvironmentKcm(QObject *parent, const KPluginMetaData &metaData)
    : KQuickConfigModule(parent, metaData)
{
    setButtons(Apply | Default);
    setAuthActionName(QStringLiteral("org.kde.nsafsm.write"));
    load();
}

QString EnvironmentKcm::userConfPath() const
{
    return QDir::homePath() + QStringLiteral("/.config/environment.d/nsa-fsm.conf");
}

QVariantList EnvironmentKcm::mapToVarList(const QMap<QString, QString> &map)
{
    QVariantList list;
    for (auto it = map.constBegin(); it != map.constEnd(); ++it) {
        QVariantMap entry;
        entry[QStringLiteral("key")] = it.key();
        entry[QStringLiteral("value")] = it.value();
        list.append(entry);
    }
    return list;
}

QMap<QString, QString> EnvironmentKcm::varListToMap(const QVariantList &list)
{
    QMap<QString, QString> map;
    for (const QVariant &v : list) {
        const QVariantMap entry = v.toMap();
        map.insert(entry.value(QStringLiteral("key")).toString(),
                   entry.value(QStringLiteral("value")).toString());
    }
    return map;
}

void EnvironmentKcm::load()
{
    // Parse /etc/environment (world-readable)
    const auto sysMap = NsaFsm::ConfigParser::parseKeyValue(QStringLiteral("/etc/environment"));
    m_systemVars = mapToVarList(sysMap);
    Q_EMIT systemVarsChanged();

    // Parse user environment.d conf (if exists)
    const QString userPath = userConfPath();
    if (QFile::exists(userPath)) {
        const auto userMap = NsaFsm::ConfigParser::parseKeyValue(userPath);
        m_userVars = mapToVarList(userMap);
    } else {
        m_userVars.clear();
    }
    Q_EMIT userVarsChanged();

    // List /etc/profile.d/ filenames
    m_profileScripts.clear();
    QDir profileDir(QStringLiteral("/etc/profile.d"));
    if (profileDir.exists()) {
        m_profileScripts = profileDir.entryList(QDir::Files | QDir::Readable, QDir::Name);
    }
    Q_EMIT profileScriptsChanged();

    setNeedsSave(false);
}

void EnvironmentKcm::defaults()
{
    load();
}

// ── System variable methods ──

void EnvironmentKcm::setSystemVar(const QString &key, const QString &value)
{
    for (int i = 0; i < m_systemVars.size(); ++i) {
        QVariantMap entry = m_systemVars[i].toMap();
        if (entry.value(QStringLiteral("key")).toString() == key) {
            entry[QStringLiteral("value")] = value;
            m_systemVars[i] = entry;
            Q_EMIT systemVarsChanged();
            setNeedsSave(true);
            return;
        }
    }
}

void EnvironmentKcm::removeSystemVar(const QString &key)
{
    for (int i = 0; i < m_systemVars.size(); ++i) {
        const QVariantMap entry = m_systemVars[i].toMap();
        if (entry.value(QStringLiteral("key")).toString() == key) {
            m_systemVars.removeAt(i);
            Q_EMIT systemVarsChanged();
            setNeedsSave(true);
            return;
        }
    }
}

void EnvironmentKcm::addSystemVar(const QString &key, const QString &value)
{
    QVariantMap entry;
    entry[QStringLiteral("key")] = key;
    entry[QStringLiteral("value")] = value;
    m_systemVars.append(entry);
    Q_EMIT systemVarsChanged();
    setNeedsSave(true);
}

// ── User variable methods ──

void EnvironmentKcm::setUserVar(const QString &key, const QString &value)
{
    for (int i = 0; i < m_userVars.size(); ++i) {
        QVariantMap entry = m_userVars[i].toMap();
        if (entry.value(QStringLiteral("key")).toString() == key) {
            entry[QStringLiteral("value")] = value;
            m_userVars[i] = entry;
            Q_EMIT userVarsChanged();
            setNeedsSave(true);
            return;
        }
    }
}

void EnvironmentKcm::removeUserVar(const QString &key)
{
    for (int i = 0; i < m_userVars.size(); ++i) {
        const QVariantMap entry = m_userVars[i].toMap();
        if (entry.value(QStringLiteral("key")).toString() == key) {
            m_userVars.removeAt(i);
            Q_EMIT userVarsChanged();
            setNeedsSave(true);
            return;
        }
    }
}

void EnvironmentKcm::addUserVar(const QString &key, const QString &value)
{
    QVariantMap entry;
    entry[QStringLiteral("key")] = key;
    entry[QStringLiteral("value")] = value;
    m_userVars.append(entry);
    Q_EMIT userVarsChanged();
    setNeedsSave(true);
}

// ── Save ──

void EnvironmentKcm::save()
{
    // 1. System vars: write /etc/environment via KAuth
    {
        const QMap<QString, QString> sysMap = varListToMap(m_systemVars);

        QString content = QStringLiteral("# Generated by NSA Fedora System Manager\n");
        for (auto it = sysMap.constBegin(); it != sysMap.constEnd(); ++it) {
            const QString &val = it.value();
            if (val.contains(QLatin1Char(' ')) || val.contains(QLatin1Char('\t'))) {
                content += it.key() + QStringLiteral("=\"") + val + QStringLiteral("\"\n");
            } else {
                content += it.key() + QLatin1Char('=') + val + QLatin1Char('\n');
            }
        }

        QVariantMap args;
        args[QStringLiteral("filePath")] = QStringLiteral("/etc/environment");
        args[QStringLiteral("content")] = content.toUtf8();

        KAuth::Action action(QStringLiteral("org.kde.nsafsm.write"));
        action.setHelperId(QStringLiteral("org.kde.nsafsm"));
        action.setArguments(args);

        KAuth::ExecuteJob *job = action.execute();
        connect(job, &KJob::result, this, [this, job] {
            if (job->error()) {
                qWarning() << "KAuth write failed (system env):" << job->errorString();
            }
        });
        job->start();
    }

    // 2. User vars: write directly to ~/.config/environment.d/nsa-fsm.conf
    {
        const QString userPath = userConfPath();
        const QDir dir = QFileInfo(userPath).absoluteDir();
        if (!dir.exists()) {
            dir.mkpath(QStringLiteral("."));
        }

        const QMap<QString, QString> userMap = varListToMap(m_userVars);
        NsaFsm::ConfigParser::writeKeyValue(userPath, userMap);
    }

    setNeedsSave(false);
}

K_PLUGIN_CLASS_WITH_JSON(EnvironmentKcm, "kcm_nsa_environment.json")

#include "environmentkcm.moc"
